.dockerignore, Dockerfile, Pipfile, Pipfile.lock, requirements.txt
First part of #9 
Change the dependencies and the docker related files
=> Dependencies and docker related changes

model_tests/main.py, model_tests/test_model_predictions.py, model_tests/test_reference_number.py, model_tests/test_reference_structuring.py, model_tests/tests_utils.py
Third part of #9 
Makes Liz's tests working with the new module architecture introduced in #14
=> Tests related changes

models.py
~~/!\ Needs a DB update before pushing live~~ ✅ 
Fix a bug where matches where inserted in the database even if they're already present by using an upsert statement. 
Fix #26 
=> Duplicates matches

main.py
Forgot to add the docstring for run predict in the last PR
=> Add docstring to run_predict

main.py, utils/__init__.py, utils/split.py
This PR zooms into the separate file and inspects the variables name to make sure they are easily understandable to a new user and are in line with how we communicate about the product externally.
Please do leave comments related to the changes I made and also if you spot anything that you be improved in terms of naming. If something is not clear now, it will probably not be in the future either so mention it.
I chose the name split for the name instead of separate since this is how we communicate this module in our presentations.
=> Rename variables, functions and file in separate

Makefile, buildspec.yml, wsf-scraper-web/Makefile
*  Add a buildspec.yml file
* Add a codepbuild-push command to the ref parser makefile
* Add a codebuild-push to the web-scraper Makefile
=> Add codepipeline related files

buildspec.yml
=> Fix yml indentation

Dockerfile, README.md, parse_latest.py, refparse.py, settings.py
This PR fix the dockerfile as a couple of files changed names.
Also fix several codestyle warnings and rename a legacy reference to the `main.py` file in the doc.
=> Fix the dockerfile for the build

Makefile
Really is to trigger the codepipeline
=> bump makefile version

README.md, refparse.py, settings.py
Updating the regex dictionary, based on work in https://github.com/wellcometrust/datalabs/pull/188
=> Update regex dictionary

policytool/.gitignore, policytool/setup.py
We need it if we want it to build on AWS
=> Commit the setup.py file that was previously ignored

README.md
Fixes for issues identified here:
https://github.com/wellcometrust/policytool/issues/67
=> Change README so it doesn't suggest code which crashes

README.md
Simple changes to the README to make it clearer where changes are required by the reader.
=> Increase clarity in sample code in README

LICENSE, README.md
As noted above, this adds a license and updates our README so it's more friendly to open source contributors and external users.
N/A
=> add MIT license & update README for early open sourcing

merge_results.py
=> Fix error on merge results when no matches are found

policytool/README.md
@aoifespenge I tagged you here because I remember you beeing interessed in what's in this table 👍
=> Add a summary of what is scraped to the readme

policytool/Makefile
=> make: fix container name now that we have multiple airflow containers

buildspec.yml
Remove policytool/ build command, because it no longer exists.
There can be...only one!
This only gets tested by CodeBuild / CodePipeline on merge.
N/A
=> buildspec.yml: only build top level dir

README.md, export_env.py, policytool/README.md, policytool/refparse/README.md, policytool/scraper/README.md
Some changes we made with Hunter adding some instruction for how to run Airflow and updating some commands and code for the setup to run.
=> Update policy tool README with latest instruction for running airflow

policytool/airflow/dags/policytool_dag.py, policytool/airflow/dags/test_dag.py, policytool/airflow/hook/wellcome_s3_hook.py, policytool/airflow/tasks/extract_refs_operator.py, policytool/refparse/refparse.py, policytool/refparse/utils/file_manager.py, policytool/refparse/utils/fuzzymatch.py, policytool/refparse/utils/hard_text_search.py, policytool/refparse/utils/parse.py, policytool/refparse/utils/s3.py
- Add `extract_refs_operator.py` which inputs parsed pdfs in json form and outputs a json gz of structured references.
- Add the hook folder and the wellcome s3 hook
- Edit `test_dag.py` to include this task
- Edit `policytool_dag.py` to include this task
- Restructure `refparse.py` so that it yields the structured references and then matches them in different functions
- Edit the settings location imports in the utils code (`settings` to `policytool.refparse.settings`) 
unittests succeed but with some warnings.
```
(virtualenv) 01763-IA-GallaghE:policytool gallaghe$ cd refparse/
(virtualenv) 01763-IA-GallaghE:refparse gallaghe$ python -m unittest
/Users/gallaghe/Code/policytool/build/virtualenv/lib/python3.7/site-packages/sklearn/base.py:253: UserWarning: Trying to unpickle estimator …
```
=> Extract ref task

policytool/web/api.py, policytool/web/static/search.css, policytool/web/static/style.css, policytool/web/static/variables.css, policytool/web/templates/base.html, policytool/web/templates/index.html, policytool/web/templates/search.html, policytool/web/test_api.py
~Finish the PR description~
Add the search backend function to the page
This PR brings up the search into policy docs content for the policytool website. 
=> Search page

README.md
As noted above, this completes updates to docs from the last PR merged, which I left out by mistake. Key parts are:
- bringing up docker env
- running local tests
- explaining what creds you need if you're at Wellcome or not
N/A
=> README.md: complete updates of README from prior PR

README.md
* Be more explicit about download path when copying evaluation data
=> Be more explicit about s3 copy path

policytool/refparse/algo_evaluation/evaluate_settings.py, policytool/refparse/evaluate_algo.py
Fixing
* paths and names for pdf_providers csv and folder that holds data
* remove length threshold from evaluate match data
=> Fix evaluate algo

Makefile
Fix tags pushed by Codebuild so they include "codebuild-latest" instead
of just "latest".
Will be tested during build on merge.
=> Makefile: use $(LATEST_TAG) during docker push

Makefile
As with the prior PR, this gets us so codebuild pushes its own tag.
Alas, but no easy way except w/in codebuild.
=> Makefile: also use $(LASTEST_TAG) for docker-build

policytool/refparse/refparse.py
Fix issue #179 
```
==================== 60 passed, 24 warnings in 3.99 seconds ====================
```
=> Fix issue #179 - dont output empty structured references

policytool/airflow/dags/policy.py
=> Fix a typo in imports

policytool/airflow/dags/policy.py
=> Fix a typo in the namedtuple attributes

policytool/airflow/tasks/fuzzy_match_refs.py
* Fix field name used for matching against EPMC titles
(doc.title, not just title)
* Truncate titles that are over 512 bytes long, since these
are probably paragraphs, and since they break queries
against ElasticSearch. See also
https://github.com/wellcometrust/policytool/issues/237
* Improve logging so we report counts during & at end, but
not each individual match.
Issue: https://github.com/wellcometrust/policytool/issues/236
```
./docker_exec.sh airflow test policy FuzzyMatchRefs.who_iris 2019-09-01
```
```
```
=> airflow: fix FuzzyMatchRefsOperator

policytool/airflow/dags/policy.py, policytool/airflow/tasks/es_index_epmc_metadata.py, policytool/airflow/tasks/es_index_fulltext_docs.py, policytool/airflow/tasks/fuzzy_match_refs.py, policytool/elastic/common.py, policytool/elastic/epmc_metadata.py, policytool/elastic/fulltext_docs.py, policytool/pdf_parser/main.py
Elasticsearch indexs are the same for the test and the main dag at the moment. This PR fixes that by assigning specific names for test and main dag runs.
Local runs of the test DAG
=> Fix elasticsearch index names

policytool/refparse/evaluate_algo.py
* Missing test files cause an IndexError, so subset away rows which could not be matched to a local reference section file.
* Add warning to advise when a file is missing.
```
make virtualenv
source build/virtualenv/bin/activate
aws s3 cp --recursive s3://datalabs-data/policy_tool_tests ./policytool/refparse/algo_evaluation/data_evaluate/
(cd ./policytool/refparse && python evaluate_algo.py)
```
=> Subset evaluate_split_section_data (Fix #249)

policytool/scraper/tests/test_parliament_spider.py
Last merge broke the build because of the new check on header. Fix it by adding some headers to the test.
Please include a summary of the changes this PR introduces for the codebase.
Also specify if some sections need special attention, and why you want to introduce this change.
Make sure to split changes across multiple pull requests, as we won't review bundled pull requests.
Finally, make sure your PR follows our code of conduct before posting (Check our [contributing guidelines](CONTRIBUTING.md) if you're not sure).
=> Fix broken build

reach/elastic/common.py, reach/elastic/epmc_metadata.py, reach/elastic/fulltext_docs.py, reach/elastic/fuzzy_matched_citations.py, reach/elastic/import_refs_from_s3.py, reach/elastic/import_sections_from_s3.py
Fixes issue #267 
Resolves issues around operations against ElasticSearch and how errors are handled, specifically when trying to operate against indexes which don't exist.
* `react/airflow/elastic/common.py` -> Added some helpers for different
clearing/creating of indices
* Updated individual modules under `react/airflow/tasks` to use common
methods implemented above
Tested and confirmed positive run of `policy-test` DAG in Airflow
=> Refactor index clearing/deleting to handle errors better (Fix #267)

reach/web/api.py, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/views/search.py
Bind the csv export button to an actual feature:
- Create a CSVExport class
- Create /search/[citations|policy-docs}/csv routes
- Bind the buttons in the templates
Local runs
=> Bind the csv export button to an actual feature

.gitignore, docker-compose.yml, reach/airflow/dags/policy.py, reach/airflow/dags/policymock.py, reach/airflow/tasks/es_index_epmc_metadata.py, reach/airflow/tasks/fuzzy_match_refs.py, reach/airflow/tasks/policy_name_normalizer.py, reach/elastic/common.py, reach/elastic/fulltext_docs.py, reach/elastic/fuzzy_matched_citations.py, reach/pdf_parser/main.py, reach/pdf_parser/objects/PdfObjects.py, reach/pdf_parser/pdf_parse.py, reach/refparse/refparse.py, reach/refparse/utils/file_manager.py, reach/scraper/wsf_scraping/file_system.py, reach/scraper/wsf_scraping/items.py, reach/scraper/wsf_scraping/spiders/acme_spider.py, reach/scraper/wsf_scraping/spiders/base_spider.py, reach/scraper/wsf_scraping/spiders/gov_spider.py, reach/scraper/wsf_scraping/spiders/msf_spider.py, reach/scraper/wsf_scraping/spiders/nice_spider.py, reach/scraper/wsf_scraping/spiders/parliament_spider.py, reach/scraper/wsf_scraping/spiders/unicef_spider.py, reach/scraper/wsf_scraping/spiders/who_iris_spider.py, requirements.txt
There's a lot of things in here. A lot more I could do but need to break down into smaller tasks now that the main bigger pieces are done.
!! This is a breaking change. The keys in the output json have changed significantly in this and have been made more consistent and renamed to reflect their contents. 
This seeks to address #302, #303, #301, #271, #126, 
- Made naming of keys more consistent
- Populates more data into resulting citations and fulltext indexes
- Adds new task for determining the policy title from available candidates
- Adds a new test_target web server to docker-compose for testing DAG flow using policy-mock DAG
- Adds new policy-mock DAG which operates against local running site to easily test DAG flow
- Updated MSF scraper to get titles from pages better
- Updates to …
=> Reach DAG refactoring to get more information

Makefile, reach/pdf_parser/tests/test_pdf_objects.py, reach/pdf_parser/tests/test_pdf_parser_tools.py, reach/scraper/tests/mock_sites/msf/1.html, reach/scraper/tests/test_who_spider.py, reach/scraper/wsf_scraping/spiders/msf_spider.py
- Fixes some tests and some issues in the MSF scraper
=> dag: Fixes to tests

reach/elastic/common.py, reach/elastic/fulltext_docs.py
- Removes keyword sub-field from policy-docs-fulltext index mapping (insertion errors)
- Adds a missing import for the json package in common.py
- Fixes a typo results -> result
- Ran airflow tasks to ensure operating correctly
- `make docker-test`
=> airflow: Various fixes

reach/web/templates/results/citations.html
=> Fix a small regression on the citations results page

docker-compose.yml
Replace a TODO in docker-compose.yml with a comment. (Sam did the work for it a couple months back)
It's a comment change, so I did not test it.
=> docker-compose.yml: replace TODO with comment

reach/web/api.py, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/views/search.py, reach/web/views/search_exports.py
Aims to close #337 
Following the recent changes to pagination/sorting, the download csv button wasn't working anymore. This PR will fix this.
It also introduce the download to json feature [note: the UI for this feature is not ready yeat, so for the time being it's only in the backend].
Local tests
=> Fix file export and add a JSON option to it

reach/web/src/css/search.css, reach/web/src/css/style.css, reach/web/src/js/app.js, reach/web/src/js/citationsTable.js, reach/web/src/js/policyTable.js, reach/web/src/js/resultsCommon.js, reach/web/templates/base.html, reach/web/templates/index.html, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/templates/search/citations.html, reach/web/templates/search/policy-docs.html
Fixes various design issues, descibed in #374 
Fix #374 
Local tests
=> 374 design fixes

reach/web/src/css/style.css, reach/web/templates/about.html, reach/web/templates/how-it-works.html, reach/web/templates/index.html, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/templates/search/citations.html, reach/web/templates/search/policy-docs.html
This PR fix #384 by updating Reach web content using provided docs.
Also fix the background shape that was stopping randomly on some pages as a drive by.
- Content update
Local runs
=> Update Reach content

reach/web/tests/test_search_api.py, reach/web/views/search.py
On staging, adding words to a the search broadens the results (OR behaviour) instead of narrowing it down (AND behaviour).
This PR fix this issue.
Fix #403 
Local runs
New tests
=> Fix a minor issue with searches

Makefile
Updating Makefile to get the ECR repository to deploy to from the codebuild environment variable
Untested, needed to test Codebuild changes made in a separate repo
=> CodeBuild supporting changes to Makefile

Makefile
Fixed a mixup in the ifdef in Makefile
=> Bugfix: Mixed up Makefile ifdefs

reach/web/templates/about.html, reach/web/templates/index.html, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/templates/search/citations.html, reach/web/templates/search/policy-docs.html
Change various texts on Reach website.
Fix #412 
- ✏️ Copy change
Local runs
=> Copy changes for Reach's website

reach/web/tests/test_search_api.py, reach/web/views/search.py
The search function didn't output exactly matched titles. This PR aims to fix that by removing punctuation, lowering case and removing empty strings.
Fix #415
=> Fix the search inputs

reach/web/src/css/results.css, reach/web/src/js/citationsTable.js, reach/web/src/js/policyTable.js, reach/web/templates/about.html, reach/web/templates/index.html, reach/web/templates/results/citations.html, reach/web/templates/search/policy-docs.html
Fix #423 (minus citation couint sorting to come in a separate PR)
Fix #425 
Fix #418
See respective issues for more details.
Local check
=> Fix issues mentionned in 423, 425 & 418

reach/web/src/js/policyTable.js, reach/web/templates/results/policy-docs.html, reach/web/templates/search/policy-docs.html
=> Remove policy docs authors

buildspec.yml, split_reach/Makefile, split_reach/scraper/spider_task.py
Updates the makefile for split_reach to get it building in the ECR pipeine
=> Setting up pipeline build commands

Makefile
=> Fixes an issue with web image ECR

.gitignore, web/Dockerfile, web/bin/docker_run.sh, web/config/docker.config.toml, web/config/local.config.toml, web/gulpfile.local.js, web/requirements.txt, web/web/api.py, web/web/config.py, web/web/src/css/contact.css, web/web/src/css/style.css, web/web/src/js/app.js, web/web/src/js/v.contact.js, web/web/templates/contact.html, web/web/utils.py, web/web/views/__init__.py, web/web/views/api/api_search_citations.py, web/web/views/api/api_search_policies.py, web/web/views/contact.py
. Adds new contact form view
. Adds in new contact post route which creates GitHub issue for contact request
. Adds a rate_limit decorator function to limit calls to the for that can be used in other sections
Other notable things:
. There is some new config associated with this, in deployment it will be configured with the wellcomedatalabs-cd uiser credentials to populate the issue.
. There is rate-limiting for the GitHub API, so we've rate-limited the POST endpoint.
. There is probably a fair bit more effort that should be done around XSRF
. We should add a recaptcha at some point potentially or some alternative, we have XSRF and a honeypot hidden field, but should make additional effort to protect against bots
Manually tested in local …
=> New Contact Form view and associated code

web/web/views/contact.py
Updated the contact page to point to a private GitHub Issues list for privacy reasons.
Untested
=> Updated GH endpoint

web/web/api.py, web/web/config.py, web/web/templates/base.html, web/web/views/template.py
This PR adds tracking code for Google Analytics and Hotjar.
Fix #537 
Local runs
=> Adds tracking capability to the base template

web/web/views/api/api_search_citations.py, web/web/views/api/api_search_policies.py
- Fix table sorting: #557
- HIdes uncited results: #548
=> Search updates - #557 #558

web/web/src/js/citationsTable.js, web/web/src/js/policyTable.js, web/web/src/js/resultsCommon.js, web/web/templates/results/citations.html, web/web/templates/results/policy-docs.html, web/web/views/api/api_search_citations.py, web/web/views/api/api_search_policies.py
This PR fix an issue with the pagination where we were missing the final page.
Also fix the sorting event being subscribed multiple time.
Local tests
=> Fix pagination and sorting in JS

web/web/src/js/app.js, web/web/src/js/citationsTable.js, web/web/src/js/policyTable.js, web/web/src/js/templates/no_results.js, web/web/templates/base.html, web/web/templates/results/citations.html, web/web/templates/results/policy-docs.html
Adds GA events to follow (See Notion for more details).
Fix #563
=> Add GA events everywhere

web/web/src/js/app.js, web/web/src/js/citationsTable.js, web/web/src/js/policyTable.js
Fix some GA labels after @aoifespenge reviewed them in the last PR
=> Fix some GA labels after Aoife review

web/web/src/js/citationsTable.js, web/web/templates/about.html, web/web/templates/base.html, web/web/templates/index.html
- Fix bug were policy links inside the citation accordion had an empty `href`
- Fix a few typos
- Add some text on About Reach for the alpha launch
=> Pre release fixes

pipeline/reach-scraper/wsf_scraping/spiders/nice_spider.py
Fix the Nice scraper not returning any docs by updating the css filter
=> Update Nice scraper to new website tags

web/web/templates/base.html
Adds the JS for Google Tag manager, allowing us to set the InternalTraffic cookie.
Local Test.
Because of its "live" nature, this needs to be tested live to ensure it's working.
=> Adds the GTM code

base/tests/mock_sites/nice/1.html
Update Nice spider's tests to fix the failing build
=> Update Nice tests after nice spider's update

web/.babelrc, web/config/docker.config.toml, web/config/local.config.toml, web/gulpfile.js, web/gulpfile.local.js, web/package-lock.json, web/package.json, web/web/api.py, web/web/src/js/app.js
Update our JS building script and fix doc static root on local
Local tests
`make web-image-build`
=> Update JS build script

base/tests/mock_sites/nice/1.html, pipeline/reach-scraper/wsf_scraping/spiders/nice_spider.py, web/.babelrc, web/config/docker.config.toml, web/config/local.config.toml, web/gulpfile.js, web/gulpfile.local.js, web/package-lock.json, web/package.json, web/web/api.py, web/web/src/js/app.js, web/web/templates/base.html
Update Reach stable release branch:
- Update Nice scraper to new website tags (#573)
- Adds the GTM code (#571)
- Update Nice tests after nice spider's update (#575)
- Update JS build script (#578)
=> Update release branch to version 2020.06.02

docker-compose.yaml, web/Dockerfile.node, web/gulpfile.js
Fix the static not all being copied to the build directory
=> Fix static image build

.github/ISSUE_TEMPLATE/enhancement_proposal.md
=> Update the new feature template according to #525

web/web/views/robotstxt.py
Update robots.txt to allow indexing.
It seems to have been missed from the launch in July.
Today marks the day, two years ago, when I joined @SamDepardieu in working on this project. So I thought it'd be nice to be able to find it on the internet, after all this time.
I tried to run `make test` per the README but it doesn't work. :shrug: :smile:
=> web: update robots.txt to allow indexing
