CONTRIBUTING.md
Add a contribution file to guide future contributors through our values, our workflow and our rules.
At the moment, it is a copy from this file -> https://www.contributor-covenant.org/version/1/4/code-of-conduct
Pretty much everything is in it, but we should make sure everything we want lives in this file.
This file should be discussed to ensure that we all agree with what is in it.
=> Add a Contributing file

Dockerfile, Makefile, main.py, models.py, requirements.txt, settings.py, utils/__init__.py, utils/file_manager.py, utils/fuzzymatch.py, utils/predict.py, utils/s3.py, utils/separate.py, utils/serialiser.py
[This PR looks big, but it's mostly due to switching back the Predictor class to a module with functions]
The reference parser had big ussues dealing with big files (e.g. the who scraping results, about 1.5Go). This PR aims to fix these issues by:
- Using multiprocessing to predict the references components and references
- Using a tempfile to read the scraping result file from S3
- Parsing the json file prior to its treatment in memory to remove big and useless chunks from it (e.g. the PDF full text)
- Indexing the database (manually done - see issue on datalabs infra for more details)
- Using an UPSERT statement instead of a SELECT and an INSERT (twice less requests to the database)
This has been tested by running pultiple tests both locally …
=> Fix the reference parser performances issues

requirements.txt
Add Click to requirements after decision to ditch Pipfile as Click is needed from `manage.py` to run the parser.
To update the requirements I did
```
pip install Click
pip freeze > requirements.txt
```
all in a separate virtualenv. This led to some additional packages added to the requirements. Let me know If you want me to follow a different process in the future.
=> Add Click to requirements

README.md, main.py, models.py, settings.py, utils/file_manager.py
This PR adapts mostly `main.py` so that it can be run with new arguments, these are:
- '--scraper-file'
- '--references-file'
- '--model-file'
- '--vectorizer-file'
- '--output-url'
Because S3 files start with 's3://' and the output url will start with 'file://' we can now distingush LOCAL and S3 runs of the code with these arguments rather than previously where we used variables in settings.
This means some parts of `settings.py` have been updated, and further work will also be needed.
I have also added `check_references_file` to `main.py` to make sure the user inputted references have the correct column names, and `get_file` to functionise a repeated process.
A small neatening of `models.py` is included in this PR.
I've run the code …
=> Allowing the S3/local distinction to be specified in arguments of main

main.py, tests/test_separate.py, utils/__init__.py, utils/predict.py, utils/separate.py
On a high level this PR will try to do the following things:
- Move split_reference to predict which is going to deal with the three steps of parsing and will work on a reference by reference level
- Refactor process_references_section so that it does not use pandas and works on 1 section at at time
- Write tests for the separate file
I am not sure whether this is the correct option for refactoring but
This PR focuses on the separate file so a test_separate file has been added under a new folder tests. You can run those tests by running `python -m unittest tests.test_separate` while on the root directory.
=> Refactor separate

README.md, main.py, tests/test_predict.py, utils/predict.py
This PR:
- Rewrites `predict_references` so that it doesn't use pandas
- Rewrites `predict_references` so that it inputs a list of components and outputs a list of tuples (prediction, probability)
- Introduces some tests for `predict_references`
- Adds a line at the beginning of `predict_structure` so that the new input (which is now a dictionary) is converted to a pd dataframe, so that this function continues to work. The aim is to eventually (in a different PR) refactor `predict_structure` so that it doesn't require a pd dataframe input, so eventually this will be redundant.
- `main` had to be updated in order to get the new output of `predict_references` into the correct format for the rest of the code.
- Fixes a small error in the README
`test_predict.py` file has been added in the …
=> Refactor predict refs

wsf-scraper-web/pdf_parser/pdf_parse.py
The pdf parseer module returning a tuple allowed to pass the
verification for an empty pdf, as `1 if (None, None) else 2` returns 1.
Fixed this by removing the old tuple returns to make them return None
instead.
Fix #52 
Local runs, unittests (Python3.6)
=> Fix the attribute error logged by sentry

wsf-scraper-web/pdf_parser/pdf_parse.py, wsf-scraper-web/wsf_scraping/settings.py
The pdf parser module could in some occasion send different results in
the tests. This commit tries to fix it by setting a specific zoom level.
This PR also changes the `WHO_YEARS` settings, as I came accross it and it was outdated.
Local and unittest (Mac OSx/Python3.6)
=> Fix an error happening sometime in pdf parsing

settings.py, utils/predict.py
Fix for https://github.com/wellcometrust/reference-parser/issues/41
Small change to `predict.py` and `settings.py` to make output contain all categories even if nothing is predicted for any of them. As in the case where no matched references are found, a file called `all_match_data.csv` is still outputted, but it will be empty.
This looks like more changes than there were due to a tab change.
It hasn't.
=> Fix #41 to deal with case of Title prediction

merge_results.py, parse_latest.py
This PR adds a python file to merge all the matched files for each documents and each organisation together into one. It joins the merged outputs with the urls and the references information. Most of the file names etc are user inputted.
I find that some of the _predicted_reference_structures files don't read in without errors (so I add a 'try'). This happens on 4 occasions and the error is:
No testing has been done.
=> Merge match results from multiple documents and organisations

refparse.py, settings.py, tests/test_fuzzy_match.py, utils/fuzzymatch.py
This PR aims to improve the readability of fuzzy matching and add tests. To achieve this we do the following
* remove batching predictions into blocks since now we process references document by document and this is not needed.
* better utilise pandas and numpy features to remove part of the code where intermediate list or tuples where introduced
* rename variables to make their function clearer, for example high_similarity_index to above_threshold_indices and use of plural indices instead of index
* taking care of empty dataframe as input which now returns an empty dataframe back
The use of pandas was not removed as its use here is satisfied. We need to perform matrix operations and return subset of matrices which is more efficient with the data structure underpining pandas. What we can …
=> Refactor fuzzy matching

Makefile, model_tests/tests_utils.py, tests/test_separate.py, utils/__init__.py, wsf-scraper-web/Makefile, wsf-scraper-web/tests/test_db_tools.py
We want to run our unittests in codepipeline before pushing the image. In order to do so, we need to add a `tests` recipe to the Makefile, and to run it prior to the `codepipeline-docker-push: push` step. 
This PR also fixes a few codestyle issues and renaming related issues.
N/A
Find a way to run tests on the database
=> Add a "make tests" command to the Makefiles

.dockerignore, Dockerfile, Makefile, README.md, wsf-scraper-web/Dockerfile, wsf-scraper-web/Makefile, wsf-scraper-web/tests/test_pdf_objects.py
The last implementation of unittests for the CI/CD pipeline couldn't work because it missed the python-virtualenv program. 
This PR aims to solve this issue by testing inside of containers instead.
To achieve this goal, we change the makefiles behaviour.
=> Enable unittests in each policytool repositories

docs/s3-layout.md
Add docs on the S3 layout, including DAG names and task names within the
DAGs.
This is an early but hopefully working outline. All feedback welcome.
N/A
N/A
=> docs: add s3-layout.md

refparse.py
On very rare occassions there are no reference components found when the references section is cleaned and split, and therefore the code fails because in `predict.py` there is no `predict_all['Predicted Category']` found.
This fixes the issue, but in the future we would like to rather than just skip processing the document, return empty lists in predict_references, predict_structure and fuzzy_match_blocks.
=> Fix #43 for when no reference components are found

utils/fuzzymatch.py
Without reseting the index when the 3 dataframes are concatenated they are done by index rather than order, causing an incorrect output.
e.g.
Previous error it caused no longer happens:
=> Reset indexes in fuzzy match

README.md, merge_results.py
This PR makes some minor improvements to merge_results, such as
* the use of same variable names as refparse, i.e. output-url and referefences-file
* remove defaults for charlene which are not justified
* adds documentation in the readme for how to run merge_results
=> Small changes to merge_results

README.md
This PR aims to make the examples in the readme run. To do so I add an s3 url that is valid for Wellcome publications and fix the path of merge results which does not use the `file://` prefix.
This is a temporary solution until we add some sample data into the repo so that a user that does not work at wellcome can run the code
=> Fix examples by adding a correct path to publications so they run

policytool/Makefile, policytool/requirements.txt
This resolves #94 :
* Address CVE-2018-16516 by upgrading flask-admin to 1.5.3.
* Update Makefile so `make virtualenv` works again, now that airflow
is a dependency.
```
```
N/A:
=> requirements.txt: address CVE-2018-16516

docs/s3-layout.md, policytool/Dockerfile, policytool/docker-compose.yml, policytool/pdf_parser/main.py, policytool/pdf_parser/pdf_parse.py, policytool/scraper/airflow/dags/policytool_dag.py, policytool/scraper/airflow/tasks/parse_pdf_operator.py, policytool/scraper/airflow/tasks/run_spiders_operator.py, policytool/scraper/wsf_scraping/file_system.py, policytool/scraper/wsf_scraping/pipelines.py
This pr aims to bring the next task on the policytool pipeline: parsing the scraped pdfs.
To achieve this:
- Rework the pdf parser module to make it task friendly:
- Now has a `main.py` file callable both from airflow or with arguments from the console
- The main file reads all pdf locations from a manifest (either locally stored or on s3), download them and extract their sections, keywords and text. It then store them in a json file on the given output location.
- Create a parser operator for airflow
- Add parsing tasks for each organisations in airflow  
Mac OSx 10.14.2 / Python 3.6:
- Local runs
- Unit testing
~~- [ ] I included tests in my PR~~ N/A
~~- [ ] If my PR aims to fix an issue, I referenced it using `#(issue)`~~ N/A
=> Add a pdf parsing task to the policy-tool DAG

refparse.py, tests/test_parse.py, tests/test_separate.py, tests/test_split.py, utils/__init__.py, utils/fuzzymatch.py, utils/parse.py, utils/predict.py, utils/split.py
This is one of the biggest refactor to date so please do review and call out any problems.
This refactor aims to achieve a couple of goals
* Remove use of pandas from predict (now named parse)
* Write tests for predict (now named parse)
* Rename variables, functions and files to make the code more readable and names more consistent
* Remove the need to document id and reference id information inside predict (now parse)
* Introduce a high level parse function called structure_reference that a accept a reference and returnes structured references
* Refactor functions in predict so that they work in one reference at at time and the code in refparse to deal with that
* Silence logger to make what is printed out less noisy but still informative
This is a big change but one that I wanted us to …
=> Refactor predict structure

tests/test_parse.py, utils/parse.py
An build error was caused when we transition from
```
references = [
reference.replace(
"-\n", ""
).replace(
"\n", " "
).replace(
"â€™", "'"
).replace(
"â€“", "-"
)
for reference in references
]
```
to 
```
components = [
elem.strip()
for elem in re.split('[,?!.]', reference)
]
```
The main difference is that this new splitting does not contain the delimiter and adds empty components so we addressed both problems. The first by changing the tests since including the delimiter is of small importance to the tool at this point. The second by filtering empty components by adding an if to the list comprehension.
`make docker-tests`
=> Fix build parse tests

refparse.py, settings.py, utils/__init__.py, utils/fuzzymatch.py, utils/hard_text_search.py
Won't be available Monday morning so adding this now. Currently runs, but has a few bugs.
@nsorros, I've encountered a bug while adding rows to `matched_references` which seems to be caused by its duplicate columns name - three of the columns are called 'index'. I currently work around that by removing columns with duplicate names on line 60 of hard_text_search.py.
Do you know what the role if these multiple index columns is/is there any issue in removing them?
=> Add hard text search to Policy Tool

README.md
At the moment, running parse latest according to method 4 throws an error if publications are not available in the default location which is not documented in the readme.
The location of the publication should be provided since the tool aims to serve an audience other than wellcome so this change introduces this parameter back in the readme and gives it the default s3 location so that in wellcome we can run parse latest regardless of local configurations, i.e. where wellcome publications are stored in our laptop
=> Add references file to method4 in Readme

README.md, refparse.py, settings.py
Fixes #81 
This could be controversial so I am happy to be rejected or altered according to your suggestions. Peter encountered a problem when running the policy tool which I had in the past as well which is that the default location for references is non present for a user and is also wellcome centric.
My opinion is that there should be no default as the publications are an input that the user provides. There should maybe a sample but every user can place their references in a different location and that is fine. This is different from the output which to a certain extent we can dictate where is placed and is also different for the scraped files since these, to a certain extent, are produced by our code. The references on the other hand are being brough by the user.
An alternative I am …
=> Remove default location for references file

policytool/Dockerfile.base, policytool/requirements.txt
We were using Debian jessie, which we can't trust anymore to have
packages listed. Also, croniter 0.3.27 is no longer present, per
similar failure found in datalabs/ repo.
Issue: https://github.com/wellcometrust/policytool/issues/115
```
```
=> policytool: fix build with newer Debian & croniter

policytool/docker-compose.yml, policytool/elastic/import_from_s3.py, policytool/requirements.txt
Brings Elasticsearch as a search service to our localdev environment. Also brings a Kibana instance to investigate the data.
This PR also adds a script to pull data from a full text dataset in s3.
Local tests, MacOs 10.14.4, Python 3.6.4, Docker@2Cpu/4GbRam
=> Add Elasticsearch to the localdev environment

policytool/Makefile
As noted in the comments, fix CodePipeline's breaking our permissions,
and thus breaking our build.
=> Makefile: set execution bit for docker_run.sh b/c CodePipeline

policytool/docker-compose.yml, policytool/elastic/import_from_s3.py, policytool/web/api.py, policytool/web/search.py
This PR brings a search route to the API.
- Define the route in api.py
- Define the service in search.py
- Change elastic/import_to_s3.py to also insert pdf_names and (randomly assigned for the time being) organisations
- Add a persistent volume to the elasticsearch container
Mac OSx 10.14.4, Python3.6.4, Docker 18.09.5 with 2CPU/4Gb RAM
=> Add a search tool to the web API

policytool/Dockerfile
On kubernetes, airflow first runs the `/airflow/initdb.sh` command. This command requires the execution privilege on the initdb file.
Mac OSx 10.14.4, Python3.6.4, Docker 18.09.5 with 2CPU/4Gb RAM
=> Allow initdb execution from the kubernetes cluster instance

policytool/refparse/utils/fuzzymatch.py
Rewrite `fuzzymatch.py` to allow single row inputs and to output only one match with the highest cosine similarity over the threshold per publication, previously it would return everything over the threshold
Fix issue https://github.com/wellcometrust/policytool/issues/139
Fix issue https://github.com/wellcometrust/policytool/issues/138
`fuzzymatch.py` would throw up an error if you tried to only match one publication (arguably this might not happen in practise though), see issue https://github.com/wellcometrust/policytool/issues/138.
This has been fixed.
It also used to output every single match over a threshold for a document, but this should have been just the best match per document. See issue https://github.com/wellcometrust/policytool/issues/139.
This has been fixed.
Please delete …
=> Fix input and output of fuzzy match

policytool/refparse/algo_evaluation/evaluate_split_section.py, policytool/refparse/evaluate_algo.py
Add metric calculation for evaluate split section and make the print out in a nice format
Note that the new functions are largely copied and pasted from [here](https://github.com/wellcometrust/datalabs/blob/bced9699254199ecff76edeca1ce80cefbaa9a01/modelling/policy/references-splitting/src/evaluate_splitter.py) (where `calc_num_metric` and `evaluate_splitter_nums` are practically the same - I return an extra variable in the latter)
This PR adds some functions to `evaluate_split_section.py` to calculate this evaluation metric.
I also edit the log file print in `evaluate_algo.py` so that it prints the information in a nice format, which now looks like:
```
-----Information about test 2:-----
Score
52.8
Percentage below threshold of 40
52.8
Median difference
29.6
Metrics grouped by source …
```
=> Add evaluate split section metric

docs/evaluation_data.md, policytool/refparse/algo_evaluation/evaluate_match_references.py, policytool/refparse/evaluate_algo.py
Similarly to the other PRs, adding the metric to `evaluate_match_references.py`. 
Since we fixed the issue of the fuzzy matcher returning multiple matches, some of `evaluate_match_references` was unnecessarily complicated for the new output of match_vectorised, so I rewrote some of it.
I was also not taking away the negative examples from the match data, so i fixed this.
Also added some info about how we got the evaluation data to the document.
The output of this test is v good, as we might expect:
```
Score
0.998
Micro average F1-score
0.998
Classification report
precision    recall  f1-score   support
0       1.00      1.00      1.00       202
1       1.00      0.99      1.00       199
micro avg       1.00      1.00      1.00       401
macro avg       1.00      1.00      1.00       401 …
```
=> Add evaluate match refs metric

README.md, docs/evaluation_data.md, policytool/pdf_parser/main.py, policytool/refparse/algo_evaluation/evaluate_find_section.py, policytool/refparse/algo_evaluation/evaluate_settings.py, policytool/refparse/evaluate_algo.py
Note you will need my testing data for this (temporary until I actually get the real policy pdf data). Download the 'pdf_sections' and 'pdfs' folders in https://s3.console.aws.amazon.com/s3/buckets/datalabs-data/policy_tool_tests/?region=us-east-2&tab=overview and put them in the 'data_evaluate' folder.
- Get the actual evaluation data! (currently test pdfs) (can still review this PR without this though, but would be nice to check it doesn't fail or anything once we have the proper data)
This involved significant work at working out how the test would work, so I have had to redesign what the evaluation data looks like, and import the new type and process accordingly (in `evaluate_algo.py`).
I have rewritten most of the layout I had designed in `evaluate_find_section.py`, and imported …
=> Add evaluate scraper metric

README.md, policytool/refparse/algo_evaluation/evaluate_find_section.py, policytool/refparse/algo_evaluation/evaluate_settings.py, policytool/refparse/evaluate_algo.py
This runs with the new real policy document data, so you need to re-download:
1. the pdf_sections folder: https://s3.console.aws.amazon.com/s3/buckets/datalabs-data/policy_tool_tests/pdf_sections/?region=us-east-2&tab=overview
2. the pdfs folder: https://s3.console.aws.amazon.com/s3/buckets/datalabs-data/policy_tool_tests/pdfs/?region=us-east-2&tab=overview
3. the new pdf metadata csv: https://s3.console.aws.amazon.com/s3/object/datalabs-data/policy_tool_tests/pdfs_providers.csv?region=us-east-2&tab=overview
This PR outputs new things for evaluation 1, mainly a breakdown of the results per provider (msf, nice...). This is all done in the `metrics_by_provider` function, but there are a few other changes since we now need to input a new file (`pdfs_providers.csv`) which gives us the …
=> Provider metadata in evaluation of find sections

policytool/pdf_parser/tools/extraction.py, policytool/resources/section_keywords.txt
- Fix #152 pdf parser regex, https://github.com/wellcometrust/policytool/issues/152
- Add 'endnote' to the list of section keywords to search for, this is backed up by having looked at a sample of pdfs and finding that endnote is more common than 'bibliograph' sections.
```
Provider                                      msf    nice  unicef  who_iris
Number of pdfs included                    15.000  17.000  31.000    32.000
Proportion with a bibliograph section       0.067   0.000   0.000     0.031
Proportion with a endnotes section          0.133   0.000   0.129     0.000
Proportion with a reference section         0.267   0.294   0.161     0.125
```
27 unittests ran OK
=> Fix how the pdf parser find sections

policytool/refparse/tests/test_fuzzy_match.py, policytool/refparse/utils/fuzzy_match.py
Fixes fuzzy matcher tests that were failing after the refactoring that was introduced in #156
=> Fix fuzzy match tests to work with refactored FuzzyMatcher

.dockerignore, policytool/refparse/algo_evaluation/evaluate_match_references.py, policytool/refparse/utils/fuzzy_match.py
I broke fuzzymatcher recently by thinking that the input to match was a dataframe, when actually it is a dict.
So in this PR:
- Fixing input to match evaluation to be a dict rather than a dataframe
- reversing the change in fuzzymatcher to not assume a dataframe
- ignoring the evluation data (which is quite large) for docker
`==================== 60 passed, 25 warnings in 4.19 seconds ====================`
=> Fix fuzzymatcher

policytool/pdf_parser/main.py, policytool/refparse/refparse.py
The old JSON format for the sections was:
`"sections":{"Reference": ['....'], "Bibliograph": ['....'], "Endnote": ['....']}`
where the keys are chosen based on what is in https://github.com/wellcometrust/policytool/blob/master/policytool/resources/section_keywords.txt
This PR fixes the problem where we were only looking for the 'Reference' section text (nothing else, i.e. bibliograph and endnote).
In this PR:
- fix pdf parser main to not capitalise dictionary keys - fixes issue #195 https://github.com/wellcometrust/policytool/issues/195 i.e. "sections":{"reference": ['....'], "bibliograph": ['....'], "endnote": ['....']}
- make section processing in refparse more generic to whatever section titles we have chosen to scrape (rather than only 'Reference')
``` …
```
=> Look for text in all the scraped section names, and uncapitalise key name

policytool/airflow/tasks/dummy_spider_operator.py, policytool/scraper/wsf_scraping/feed_storage.py, policytool/scraper/wsf_scraping/file_system.py
Issue: https://github.com/wellcometrust/policytool/issues/192
While testing SSO credentials it became clear that scrapes are
running "to completion" even when the pipeline fails to complete,
or when items failed to be saved. Fix this by adding Scrapy signal
handlers to our airflow task, and by firing an additional signal
if we failed to write the final manifest file at the end of the
pipeline.
Other changes:
* Fix duplicate (and verbose -- boto debug logs were getting thrown in)
logging by making our Crawler not add a root handler.
* Log scrapy settings on a single line; it was super long otherwise.
* Report exceptions in our blocking thread to Sentry, since
they won't show up in the Twisted error log.
* Note that our item pipeline's uploader is blocking (!).
Please delete options that …
=> policytool: make airflow scrapy tasks fail

Makefile, docker-compose.yml, policytool/airflow/safe_import.py, policytool/airflow/tasks/es_index_publications.py, policytool/airflow/tasks/exact_match_refs_operator.py, policytool/airflow/tasks/extract_refs_operator.py, policytool/airflow/tasks/fuzzy_match_refs_operator.py, policytool/airflow/tasks/parse_pdf_operator.py, requirements.txt
airflow: only import ML libs on execute
Resolve (we hope) a persistent issue and cause of incidents:
import time for DAGs takes an unreliably bounded amount of time,
resulting in Airflow's web UI raising an AirflowTaskTimeout
(which isn't really for a task at all...but oh well). Key changes:
* Add a library for safely importing modules from within Airflow
task execute() methods.
* Move heavy imports for all ML tasks into their execute() methods.
Also fix a typo in airflow.tasks.es_index_publications.
https://github.com/wellcometrust/policytool/issues/194
https://github.com/wellcometrust/datalabs-infra/issues/203
https://github.com/wellcometrust/datalabs-infra/issues/209
* `make docker-test`.
* Ran test DAG locally.
* Manually verified exceptions raise by running thread w/time.sleep() and …
=> Import on execute

policytool/web/bin/docker_run.sh
This PR aims to fix the build error that occured on build policytool:af97e75c-7be0-4dcf-bcae-2467c8ee0cdd
by changing the image name in the docker_run file of the web project.
```
make test
make docker-build
make web-image-build
```
=> Fix image name in web's docker_run file

policytool/pdf_parser/main.py
The pdf parser wrote null to the output file when it couldn't parse a
pdf. This caused the next task to sometime be unable to read the json
file.
(See #214 )
=> Write a dict instead of null for unparsed pdfs

policytool/scraper/wsf_scraping/pipelines.py
Current version of the scrapers on staging runs out of disk on full runs. At the moment, we're not removing downloaded pdf tempfiles dureing the process. This PR adds a `os.unlink` command to try to remedy to the disk shortage by removing already uploaded pdf files.
Note that this fix may not completly fix the disk issue.
See https://github.com/wellcometrust/datalabs-infra/issues/232 for more details about the issue.
`make test`
Local runs on Mac OS 10.14.6, with Docker @ 2CPU/10.5GiB RAM
=> Add a file removal in the scraper's pipeline

policytool/pdf_parser/main.py, policytool/scraper/wsf_scraping/file_system.py
Add's start-time, end-time and organisation fields to the manifest
Also ignore those fields in the pdf parser task.
Local tests
`make test`
=> Add some fields to the scraper's manifest

docker-compose.yml, policytool/airflow/dags/policy.py, policytool/airflow/tasks/fuzzy_match_refs.py
* Configure ES hosts by environment variable
* Add FuzzyMatchRefsOperator to main & test DAGs
* Update FuzzyMatchRefsOperator to use the right ES index name
Test DAG runs successfully. As does:
```
```
=> airflow: add fuzzy matcher back to DAG

policytool/scraper/wsf_scraping/pipelines.py
The first attempt at fixing this failed because all files (up to point
of node disk pressure & pod eviction) were already present in the
manifest, and thus the unlink never occurred. Fix this by:
* no longer raising DropItem (we don't have any more steps in the
pipeline anymore anyway), so that we always unlink.
* also using the correct path for deleting the file (item['pdf'] is
an absolute path)
Issue: https://github.com/wellcometrust/policytool/issues/220
`make docker-test` (though this won't reach this code path...sadly)
=> scraper: fix logic for deleting PDFs post scrape

policytool/airflow/tasks/parse_pdf_operator.py, policytool/pdf_parser/main.py, policytool/pdf_parser/pdf_parse.py
* Fix parse_all_pdf() so that it doesn't accumulate all text into memory
before writing to disk.
* Fix parse_all_pdf() so that it deletes PDF files after parsing
* Update parse_all_pdf() so that it writes chunks from the network
to tempfile instead of downloading all of it into memory at once.
* Fix parse_pdf_document() so that it takes a named tempfile and so
that it uses a dedicated tempfile, so that we don't proliferate XML
files when parse fails.
* Remove manifest from output URL (output is jsonl, not a scraper
manifest).
* Fix CLI for policytool.pdf_parser.main & give example.
* Configure logging for CLI for policytool.pdf_parser.main.
Issue: https://github.com/wellcometrust/policytool/issues/224
Please delete options that are not relevantx
```
python -m policytool.pdf_parser.main \ …
```
=> pdf_parser, airflow: fix memory & file leaks

policytool/pdf_parser/main.py, policytool/pdf_parser/pdf_parse.py, policytool/pdf_parser/tests/test_pdf_objects.py, policytool/pdf_parser/tests/test_pdf_parser_tools.py
Some PDF files have caused our airflow worker to OOM. Remediate this
by skipping these files (which, on inspection of one at least, didn't
contain any useable data):
* Skip PDF files where pdf2html output is > 64MB
* Update parse_pdf_document() so it returns parse errors
* Include PDF parse errors in JSON output, so we can track how many
parses fail and of what kind
* ~~Use LXML instead of BeautifulSoup for parsing HTML (faster, may be
more memory efficient)~~
Issue: https://github.com/wellcometrust/policytool/issues/227
```
./docker_exec.sh airflow test policy ParsePdf.who_iris 2019-09-01
```
using a `docker-compose.yml` that pointed to `s3://datalabs-staging/`, and where the manifest was updated to only include files with hash prefix of `69`. …
=> pdf_parser: skip pdf2html outputs > 64MB

policytool/scraper/tests/mock_sites/gov/1.html, policytool/scraper/tests/mock_sites/gov/2.html, policytool/scraper/tests/test_gov_spider.py, policytool/scraper/wsf_scraping/settings.py, policytool/scraper/wsf_scraping/spiders/gov_spider.py
Gov.uk spider wasn't writting anything, neither into pdfs nor into the manifest. This PR aims to fix that by the following fixes:
- Fix the css classes used to find the pdf urls
- Switch the dupefilter class to something that actually filters
- Update gov_uk spider's tests
See issue: #200 For more information
`make test`
Local runs on MacOS 10.14.6 - Docker / Docker Compose
=> Fix gov scraping

policytool/airflow/dags/policy.py, policytool/elastic/common.py
Two small changes:
1. Use the same index name for all policy documents we index.
1. Add a minimal CLI for obtaining an ElasticSearch client, via `python -i -m policytool.elastic.common`
(feature?)
1. Running test & main DAG on EC2 instance.
1. `make docker-test`
=> Use single index for policy docs; add cli

policytool/airflow/tasks/fuzzy_match_refs.py
Fix cases where there are no references to match, such as we see when
running the test DAG in staging.
Issue: https://github.com/wellcometrust/policytool/issues/241
=> airflow: fix fuzzy match when no refs to match

policytool/refparse/README.md
Very small change to scraped data location.
Fixes issue #193
Running the new command in the virtualenv worked and started to parse and match the references (before I quit it).
=> Update refparse scraped JSON example in README to one that will work

policytool/scraper/wsf_scraping/file_system.py, policytool/scraper/wsf_scraping/items.py, policytool/scraper/wsf_scraping/spiders/base_spider.py
The lack of url attribute is blocking right now (#244 ) so this PR adds a 'data' section to the manifest file as a temporary fix.
This is non-optimal and need changes, as it duplicates the file_hash as dict key. On the other hand, it doesn't affect anything else on the DAG so everything else can run normally.
Fix #244 
Local runs on Docker with 2CPU, 10.5GiB:
- `./docker_exec.sh airflow test policy-test Spider.msf 2019-10-02`
- Verification of the produced json file
=> Add urls back to the manifest file

policytool/scraper/wsf_scraping/spiders/base_spider.py
Requests forbidden by robots.txt iles where wrongly logged into sentry. This commit filter them and treat them as warnings.
Fix #191 
```
```
Local runs using Docker with 2CPU and 10.5GiB:
```
./docker_exec.sh airflow test policy Spider.unicef 2019-10-07
```
(On a new scrape, UNICEF has 4 robots.txt forbidden requests right at the beginning)
=> Fix robots.txt reporting to sentry

policytool/scraper/wsf_scraping/spiders/parliament_spider.py
Parliament scraping has been crashing before it finishes lately, because of the huge number of publication it's trying to pull. Most of those publications are not useful to us, so considering that, we decided to limit what gets scraped from the parliament website.
In addition to that, this PR also fixes a bug where the parliament spider only checked for pdf header, and ended up trying to get the css atribute of `.doc` or `.xls` documents.
- gov_uk spider: Update the search url (fix #226 )
- gov_uk spider: Check if the reponse is a text response (Fix #222 )
Local runs on Docker with 2CPU 10.5GiB:
```
./docker_exec.sh airflow test policy Spider.parliament 2019-10-03
```
=> Fix parliament scraping

policytool/airflow/dags/policy.py, policytool/airflow/tasks/es_index_fuzzy_matched.py, policytool/elastic/fulltext_docs.py, policytool/elastic/fuzzy_matched_citations.py
This PR adds the indexion of all citation matched in the fuzzy matching task of the airflow pipeline.
- Adds `fuzzy_matched_citations.py` to the elastic module
- Adds `es_index_fuzzy_matched.py` to the airflow tasks
- Adds the task to the main and test DAG
- Fix an incoherence in elastic's `fulltext_docs.py`
Local runs using Docker with 2CPU, 10.5GiB memory:
- policy-test ✅ 
- policy ✅
=> Index citations from fuzzy matcher

policytool/pdf_parser/pdf_parse.py
Fix an uncatched exception on the pdf parser where lxml had to parse wrongly syntaxed xml files.
Fix #255
=> Catch xml parsing exceptions

policytool/airflow/dags/policy.py, policytool/airflow/tasks/es_index_fulltext_docs.py, policytool/airflow/tasks/es_index_fuzzy_matched.py, policytool/elastic/fulltext_docs.py, policytool/elastic/fuzzy_matched_citations.py
🚨 This will change the name of the indices used in Elasticsearch 🚨 
Fix a few incoherence on ES indices:
- No more indices called "policy-policy-X" or "policy-policy-test-X", just "policy-X" or "policy-test-X"
- Fixed an issue where we only kept the last organisation results (one task per organisation, but full index clean every task)
Local test and full runs on Docker with 2CPU, 10.5GiB memory
=> Fix Elasticsearch indices

docker-compose.yml
Updates to `docker-compose` to 
* Updated elasticsearch image to 7.2.1 from 7.2.0 as there was an issue
in 7.2.0 with a file creation race of some type (more information here https://github.com/elastic/cloud-on-k8s/issues/1076)
* Updated JVM options for elastic search to start with a lower heap
allocation than max heap allocation to speed up start and avoid
`OutOfMemory` issues.
* Added `depends_on` param to `web` service for elasticsearch to avoid help mitigate races on startup of containers.
Untracked issues, arising from initial set up of repo for local development.
- [x ] :bug: Bug fix
Local testing of run of `docker-compose` and confirmation that all services are running.
```
➜  reach git:(update-dev-docker-setup) docker-compose ps
WARNING: The AWS_SESSION_TOKEN variable is not set. …
```
=> docker-compose: Updates to make running local dev smoother

reach/web/Dockerfile.node, reach/web/gulpfile.js
* gulp build path didn't match with -v mount in `docker_run.sh`
* Dockerfile.node VOLUMES did not match against  args and commands
Changes tested manually locally from a clean slate state.
=> gulp: Path/Volume fixes (Fix #266)

Dockerfile, Dockerfile.base, Makefile, docker-compose.yml, reach/airflow/airflow.cfg, reach/airflow/initdb.sh, reach/web/Dockerfile.node, reach/web/bin/docker_run.sh, reach/web/gulpfile.js
**Note** There are appropriate changes coming to the infra repo in support of these changes as well. As well, as I'm relatively new to the repo, if there's anything I've missed or not considered please let me know and I'll revise.
* Updated file paths to be based in  folder inside containers versus the root of the file system
* Updated gulp watch and gupl build paths to use new paths in
* Updated airflow and other dependents to use  filepaths
* Organized copies into  and  folders under opt for easier debugging inside of containers
This commit mainly consists of changes to various path configurations throughout in order to get a more concrete clean set of directories set up with predictable paths.
The main issue this addresses is that up until this change files, and folders were being …
=> docker and docker-compose: Updates to file paths to clean up dirs (Fix #266)

CONTRIBUTING.md, README.md, docker-compose.yml, export_wellcome_env.py
Our existing README & tooling required you to have AWS creds capable of decrypting Wellcome-specific ciphertext. Make it so that's not the case, and update docs accordingly. Also update docs to include a note on commit message style.
* Running `docker-compose up` without the additional env vars.
* Running `export_wellcome_env.py` and verifying it prints SENTRY_DSN.
=> Remove dependency on export_env.py; update docs

reach/airflow/dags/policy.py, reach/airflow/tasks/extract_refs_operator.py, reach/refparse/refparse.py, reach/refparse/settings.py
Update the reach reference parser so that it uses the model checked into
the repo by default, instead of pulling from an arbitrary location in
S3.
Also, remove related settings from refparse/settings.py.
Refactor.
1. `make docker-test`
1. Running the `policy-test` DAG from a fresh EC2 instance.
1. Running the `refparse` command line per the README.
=> reach: make refparse default to local model file

reach/scraper/tests/mock_sites/gov/3.html, reach/scraper/tests/test_gov_spider.py, reach/scraper/tests/test_msf_spider.py, reach/scraper/tests/test_nice_spider.py, reach/scraper/tests/test_parliament_spider.py, reach/scraper/tests/test_scraper_spiders.py, reach/scraper/tests/test_unicef_spider.py, reach/scraper/tests/test_who_spider.py, reach/scraper/wsf_scraping/spiders/base_spider.py, reach/scraper/wsf_scraping/spiders/gov_spider.py, reach/scraper/wsf_scraping/spiders/msf_spider.py, reach/scraper/wsf_scraping/spiders/nice_spider.py, reach/scraper/wsf_scraping/spiders/parliament_spider.py, reach/scraper/wsf_scraping/spiders/unicef_spider.py, reach/scraper/wsf_scraping/spiders/who_iris_spider.py
This pull is to fix #261 see that issue for the specific details of the issue.
* Adds new `_is_valid_pdf` and `_is_valid_pdf_url` methods to `base_spider.py` which filter on headers as well as the URL fragment for selecting appropriate PDF files for download.
=> scraper/parliament: Fix an issue with file:/// protocol URLs Fix #261

reach/web/api.py, reach/web/views/robotstxt.py
Extend reach/web/api.py so that it serves GET /robots.txt requests.
```
curl http://localhost:8081/robots.txt
```
=> reach/web: disable search engine indexing

reach/airflow/dags/policy.py, reach/scraper/wsf_scraping/middlewares.py, reach/scraper/wsf_scraping/settings.py, reach/scraper/wsf_scraping/spiders/gov_spider.py
New middleware which allows specifying  parameter in spider subclasses
which allows blocking of crawls to sites which are known to cause issues (i.e. beta.hfea.gov.uk)
from the gov scraper.
Running policy-test DAG with `disallowed_hosts` set to known domains that show up in the policy-test crawl for a given spider (i.e. for the gov scraper disallowing crawls on gov.uk)
=> spider: Adding a new additional middleware Fix #275

reach/web/.dockerignore, reach/web/package.json, reach/web/src/css/results.css, reach/web/src/images/Icon_Research_24px.svg, reach/web/src/js/app.js, reach/web/src/js/sortTables.js, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/views/search.py
This PR adds sorting and pagination to the tables on Reach's web application.
- Add List.js to the packages
- Create some nice JS script to add sorting and pagination
- Bit of rework on both result pages to allow pagination and sorting to happen
local runs and tests
=> Add sorting and pagination to the tables

reach/web/src/js/sortTables.js, reach/web/templates/results/citations.html
As a temporary change, adding an extracted title column while we set up the nice accordion rows on the result table.
=> Add the extracted title to the table

requirements.txt
There's an issue with airflow 1.10.6 which has broken our pipeline, downgading
to 1.10.5 resovles the issue for now, will schedule testing the newer version
in the next sprint to see what needs to be changed in order to resolve the issue.
=> airflow: Downgrading from 1.10.6 to 1.10.5 Fix #298

reach/airflow/dags/data_flow_testing.py
Renamed test_data_flow to data_flow_testing in dags as this was causing a pytest
to pick up the file and failing the build.
=> Bugfix: Filename breaking builds/tests (Untracked)

reach/elastic/common.py
Fixes #309 
• Fixes an issue in elastic/common.clear_index_by_org where the key isn't correctly set resulting in duplicates in elastic on multiple subsequent runs of the DAG
Running the DAG task to ensure previous results are cleared from the index.
=> Bugfix: query filter incorrect for elastic Fix #309

requirements.txt
Downgrading airflow back to 1.10.4 as 1.10.5 has a breaking change in how it sets up configuration
Untested
=> Bugfix: Downgrade airflow due to breaking changes

reach/airflow/dags/policy.py, reach/airflow/tasks/fuzzy_match_refs.py, reach/airflow/tasks/policy_name_normalizer.py, reach/pdf_parser/pdf_parse.py, reach/pdf_parser/tools/extraction.py
Fix #183 
We find repeated chunks of text when getting the sections, despite the repeated text not being in the full text scrape.
This bug was in the grab sections code.
e.g.
Before the references section grabbed from [this document](https://www.nice.org.uk/guidance/ph31/resources/unintentional-injuries-on-the-road-interventions-for-under-15s-pdf-1996292434885) was repeating the 1st page of references:
```
"References\nReferences\nAudit Commission and Healthcare Commission (2007) Better safe than sorry: preventing\nunintentional injury to children. London: Audit Commission\nDavis R, Pless B (2001) BMJ bans 'accident'. BMJ 322: 1320–1\nDepartment for Transport (2007) Child road safety strategy 2007. London: Department for\nTransport.\nDepartment for Transport (2008) Road casualties Great …
```
=> Fix grab section duplications

reach/scraper/wsf_scraping/spiders/unicef_spider.py
We are currently scraping titles from Unicef (e.g. https://data.unicef.org/resources/child-protection-resource-pack/) using a css selector for a class that doesn't exist, which caused the scraped titles to be null. The proposed changes fixes this behaviour. 
`make test` and `make docker-test`. 
All tests pass, except for fuzzy match test that `xfails`:
```
collected 75 items                                                                                                                                                                                         
reach/pdf_parser/tests/test_db_tools.py ..
reach/pdf_parser/tests/test_pdf_objects.py ..........ss.
reach/pdf_parser/tests/test_pdf_parser_tools.py .... …
```
=> Fix Unicef title crawling

reach/airflow/tasks/fuzzy_match_refs.py, reach/elastic/common.py, reach/elastic/fuzzy_matched_citations.py, reach/web/src/css/icons.css, reach/web/src/css/results.css, reach/web/src/css/style.css, reach/web/src/js/citationsTable.js, reach/web/templates/results/citations.html, reach/web/views/search.py
This PR aim to bring the collapsible rows feature to Reach's web application. To provide this feature:
- Change the behaviour of the fuzzymatching task to save research papers' related policy docs in a dedicated list field (`policies`).
- Refactor the `_search_es` function, as it is not needed anymore to have two different (grouping done beforehand)
- Rewrite the JS refresh class to account for collapsible rows
- Add dedicated classes in CSS in order to match the mockups in Zepplin
Local tests with Docker (2CPU/10.5GiB/1.0GiBSwap)
=> Group policy documents by research paper in Reach web app

reach/airflow/tasks/fuzzy_match_refs.py, reach/pdf_parser/pdf_parse.py, reach/refparse/refparse.py
Fix for #331 
Fixes an issue where sections were getting populated downstream unnecessarily
- policy-mock dag run and check
- `make docker-test`
=> DAG data propagation issue Fix #331

reach/airflow/tasks/fuzzy_match_refs.py
Fixes an issues where a logging call is referencing an incorrect key value.
Issue was raised from alert manager
=> airflow: Update a logging output to reference correct key name

reach/pdf_parser/pdf_parse.py
Aiming to fix issue #363, where metadata cannot be decoded from unicode. After reviewing catching the error and trying to decode with an alternate encoding, felt the best call was to just skip the characters that can't be decoded. Shouldn't raise any exceptions and therefore shouldn't disrupt the DAG at all. 
Also, set metadata keys to be lowercase so 'title' and 'Title' can both be extracted.
Tested this locally on a handful of PDFs.
=> Pdf metadata encoding Fix #363

reach/scraper/wsf_scraping/spiders/base_spider.py
Aimed to fix #353. List index out of range was being caused in this case by a header that ended with a semi-colon. 
```
b'attachment; filename="CD_OFSM-ECS.pdf";'
```
When split on the semi-colon this left a list with no '=', which then could obviously not be split into a sublist of two items. Fixed this by checking that each item contains an '=' before that second split.
Also, removed the `item[1] or None` on line 167 as this wasn't returning None when the index didn't exist. 
Finally, I also stripped the item[0] key as in the same example it was set to ' filename' with that whitespace stopping the next few lines from extracting the filename.  
Tested locally and ran `make docker-test`
=> Scraper list index Fix #353

reach/web/src/js/resultsCommon.js, reach/web/templates/results/citations.html, reach/web/templates/results/policy-docs.html, reach/web/templates/search/citations.html, reach/web/templates/search/policy-docs.html, reach/web/tests/test_search_api.py, reach/web/views/search.py
This PR aims to improve the search feature in Reach by adding a way to search for multiple terms in multiple fields in the form of comma separated parameters (e.g. `terms=malaria,dog,foo&fields=title,title,text`).
It also splits the query building step from the actual query to ES and include a new test for this query building method.
This is meant to fix #328 .
What's not in this PR:
- Related frontend is still using the one term -> all fields style query (some ajustment have been made to keep it working)
- API documentation (to come next in a follow up PR)
Local runs on Docker with 2CPU/10.5GiB/1GiBSwap
=> Add a way to query multiple terms/fields to Reach API

Makefile, reach/airflow/dags/match_annotated_titles.py, reach/airflow/dags/policy.py, reach/airflow/tasks/evaluator.py, requirements.txt
Adds a series of tasks required to complete an end-to-end evaluation of reach by comparing the results from the policy dag with manually labelled validation (gold) data (https://trello.com/c/BD44uSl6/922-add-end-to-end-evaluation-to-airflow-policy-dag).
Two tasks are added to the existing `policy` and `policy-test` dags yielding the following dags:
`policy`:
`policy-test`:
An additional dag (`match_annotated_titles`) is also added to ensure that the same logic for matching references found by reach can also be used for manual labelling. The output of this dag would then be manually verified, and uploaded to s3 where it can be accessed by the `policy` and `policy-test` by `evaluator.EvaluateOperator()`. The `match_annotated_titles` dag looks like:
NOTE: There remains an issue with fuzzy …
=> Add Reach end-to-end evaluation to policy dag

reach/scraper/tests/mock_sites/unicef/1.html, reach/scraper/wsf_scraping/items.py, reach/scraper/wsf_scraping/spiders/base_spider.py, reach/scraper/wsf_scraping/spiders/unicef_spider.py
Fix #325 
Fix #352 as a drive-by issue
Unicef updated their design, this PR changes the scraper accordingly.
Also fix an issue with the titles gettings pulled from the headers as bytes (non-json serialisable).
Local runs of parliament scraping
=> Fix UNICEF scraper

reach/airflow/dags/match_annotated_titles.py, reach/airflow/dags/policy.py, reach/airflow/tasks/evaluator.py, reach/airflow/tasks/fuzzy_match_refs.py
Fixes issues with the end to end evaluation introduce in #341, primarily documented in #367. The main changes this PR introduces are:
* Splits `EvaluateExtractRegsFromGoldData` into to separate tasks for easier debugging.
* References found in the manually tagged data that cannot be pinned to a document id will be discarded for the purposes of the end to end evaluation.
* Moved specification of elastic search parameters to the policy dag specification so that these can be passed to the `EvaluateOperator` and recorded for comparison with results.
* Solves most pressing issue with matches differing from local runs (#367) by creating a dummy `reference_id` based on a hash of the title. Future versions may allow the `reference_id` to be recreated in the annotation environment once other …
=> Fix issues in gold reference extraction (Fix #367)

reach/airflow/dags/policy.py
To create a historical record of Reach results, this PR adds a timestamp to the output evaluation files. This is implemented using the `{{ ts_nodash }}` jinja template and will get recreated when a new dag is run, _not_ when the task is manually triggered from the command line or GUI.
The output of the end-to-end evaluation will now be stored in two timestamp files, e.g.:
```
s3://datalabs-dev/reach-airflow/output/policy-test/evaluation/fuzzy-matched-reach-refs/20200124T035155-evaluation-fuzzy-matched-reach-refs.json.gz
s3://datalabs-dev/reach-airflow/output/policy-test/evaluation/results/20200124T035155-evaluation-results.json.gz
```
The second file depends on the first, and the second file is only intended to be read by humans for now.
Components tested individually in dev environment. …
=> Save end-to-end evaluation outputs with timestamp

reach/scraper/wsf_scraping/items.py, reach/scraper/wsf_scraping/pipelines.py
Adds the PDF DocumentID as a key in the scraped PDFs metadata
=> - Adds the DocumentID as a key in the scraped PDFs metadata

reach/web/tests/test_search_api.py, reach/web/views/search.py
This PR fix #381 by splitting the terms of the queries by spaces before querying the database. This behaviour is due to ES way of querying texts (see match queries vs term query -> https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html#avoid-term-query-text-fields ).
This PR also now tests for the query builder to generate a correct set of terms for the queried field if the query included spaces (aka was a sentence)
Local runs
New tests
=> Fix an issue where user couldn't search multiple words

reach/airflow/dags/policy.py
**Note** This is a bandaid fix while we sort out the resource utilization in the cluster.
Adds retries to dag tasks to allow it to re-attempt scheduling a task when it fails, this is being added in order to work around the limitation of running the ExtractRefs concurrently
=> DAG Retries

reach/airflow/tasks/fuzzy_match_refs.py, reach/web/templates/results/citations.html
A sort by number of associated policy documents is needed for usability testing. This PR adds this field to the citations and adds a sortable column to the results table for citation.
Fix #423 
Local runs
=> Implement the sort by policy docs count

reach/airflow/tasks/fuzzy_match_refs.py
Fix a typo in the fuzzy matching task where it tried to increment the number of policy document in ['policies'] instead of the root key
=> Fix a wrong key inthe fuzzy match task

reach/web/templates/results/policy-docs.html
Remove the authors column headers again from the policy docs results page.
=> Remove authors column header again

split_reach/Makefile
Upgrade to the makefile to make it possible to build all images in one command.
It is now possible to build everything using `make docker-build`, as intented.
=> Update Makefile to build ECR images all in one recipe

split_reach/extracter/refparse/refparse.py
This is a temporary fix in the current version of the deep reference parser used by Reach to not get the error
```
Traceback (most recent call last):
File "./extract_refs_task.py", line 104, in <module>
extracter.execute()
File "/opt/reach/hooks/sentry.py", line 21, in wrapped_f
return f(*args, **kwargs)
File "./extract_refs_task.py", line 56, in execute
for split_references, parsed_references in refs:
File "/opt/reach/refparse/refparse.py", line 183, in yield_structured_references
doc.section
File "/usr/local/lib/python3.6/site-packages/deep_reference_parser/split_section.py", line 78, in split
doc = nlp(text)
File "/usr/local/lib/python3.6/site-packages/spacy/language.py", line 392, in __call__
Errors.E088.format(length=len(text), max_length=self.max_length)
ValueError: [E088] Text of …
```
=> Use less characters in text to be split

Makefile, pipeline/reach-fuzzy-matcher/fuzzymatcher_task.py
Reach fuzzy-matcher task had a few issues:
- No defaults for `should_match_threshold` and `score_threshold`, leading to some issue with the ES query
- Fix a typo in the dict index we use to store `associated_policy_docs`
Local runs
Runs on staging argo
=> Fix fuzzymatcher task

web/web/src/js/citationsTable.js, web/web/src/js/policyTable.js, web/web/src/js/resultsCommon.js, web/web/src/js/templates/no_results.js, web/web/templates/contact.html, web/web/templates/results/citations.html, web/web/templates/results/policy-docs.html, web/web/views/api/api_search_citations.py, web/web/views/api/api_search_policies.py
This PR upgrade Reach's Frontend to use the new API relying on PSQL:
- Templates now returns mock rows on first load
- No results page is now an html rendered JS template litteral 
- Upgrade Reach brand to include `alpha` on contact page
Local tests (Relying on prod database's data
=> Rewrite Reach Frontend to account for new PSQL backend

web/web/src/js/citationsTable.js, web/web/src/js/templates/no_results.js, web/web/templates/about.html, web/web/templates/index.html, web/web/templates/results/citations.html, web/web/templates/results/policy-docs.html
-  Use link to contact page instead of email in all contact copies (Fix #533 )
Local checks
=> Update contact links

pipeline/reach-fuzzy-matcher/fuzzymatcher_task.py
Fixes an issue when there are no citations to write resulting in an empty gzip file being pushed down the chain breaking other pipeline tasks
=> Fuzzymatcher Output Fix

Makefile
This change is compatible with AWS CLI version >= 1.17.10.
See https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html\#cliv2-migration-ecr-get-login for more details.
=> Update the Makefile with the AWS-CLI2 get-login-password.

Makefile, base/hooks/s3hook.py, pipeline/reach-evaluator/Dockerfile, pipeline/reach-evaluator/evaluator_task.py, pipeline/reach-evaluator/requirements.txt
**Something horrible happened in the previous PR so this is a redo of https://github.com/wellcometrust/reach/pull/516**
There is now scraper data for an organisation called 'evaluation'. So this would be the starting point for the evaluation flow, which would look like:
```
ORG = evaluation
make run-parser
make run-extracter
make run-indexer-fulltexts
make run-indexer-epmc
make run-fuzzymatcher
make run-evaluator
```
Not sure how the argo flow would actually be coded though! But this is how it would work running locally).
- These changes work and give reasonable output files when I run things locally, but I worry I haven't edited other files which will allow them to be run in production. Can you comment on that?
Incorporating the end to end evaluation - …
=> REDO End to end evaluation pipeline tasks

pipeline/reach-es-extractor/requirements.txt
Bumps the version being loaded for deep_reference_parser in the reach-es-extractor task.
=> Bumping deep_reference_parser version

Makefile, pipeline/reach-fuzzy-matcher/fuzzymatcher_task.py
Citations were grouped by extracted reference id. Some of the extracted references have slightly different titles
because of spacing, casing or fuzzymatching. We are now using the matched reference id instead to group the citations.
Fix #596 
=> Fix citations not grouping together
